package com.example.expenseutility.constants;

import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class ExpenseConstants {

    public static final float ANN_INCOME = 86000.0f;
    public static final List<String> SUGGESTION_LIST = Collections.unmodifiableList(Arrays.asList(
            "Taxi", "Fuel", "Mortgage", "Coffee", "Tea", "Juice", "Soda", "Alcohol",
            "Wine", "Beer", "Tobacco", "Cigarettes", "Newspaper", "Magazine", "Park",
            "Cinema", "Theater", "Concert", "Zoo", "Museum", "Swimming", "Gaming",
            "Lottery", "Betting", "Savings", "Investment", "Stocks", "Mutual", "Gold",
            "Jewelry", "Watch", "Perfume", "Deodorant", "Shampoo", "Soap", "Toothpaste",
            "Brush", "Comb", "Towel", "Bedsheet", "Pillow", "Blanket", "Curtains",
            "Carpet", "Painting", "Vase", "Clock", "Lamp", "Battery", "Bulb", "Candle",
            "Matches", "Lighter", "Umbrella", "Bag", "Wallet", "Belt", "Hat", "Scarf",
            "Gloves", "Sunglasses", "Sunscreen", "Mosquito", "Repellent", "Disinfectant",
            "Detergent", "Bleach", "Cleaner", "Broom", "Mop", "Bucket", "Sponge",
            "Tissue", "Napkin", "Diapers", "Sanitary", "Condoms", "Contraceptives",
            "Vitamins", "Protein", "Whey", "Creatine", "Bandage", "Ointment", "Syrup",
            "Inhaler", "Vaccination", "Xray", "Scan", "Surgery", "Ambulance",
            "Physiotherapy", "Counseling", "Yoga", "Meditation", "Pilates", "Zumba",
            "Aerobics", "Cycling", "Running", "Walking", "Trekking", "Camping",
            "Fishing", "Hunting", "Photography", "Gardening", "Cooking", "Baking",
            "Knitting", "Sewing", "Drawing", "Sculpting", "Pottery", "Writing",
            "Reading", "Podcast", "Audiobook", "Documentary", "Opera", "Ballet",
            "Exhibition", "Festival", "Carnival", "Fair", "Circus", "Aquarium",
            "Planetarium", "Observatory", "Library", "Bookstore", "Stationery", "Pen",
            "Pencil", "Eraser", "Sharpener", "Stapler", "Punch", "Glue", "Tape",
            "Scissors", "Cutter", "Ruler", "Compass", "Calculator", "Diary", "Notebook",
            "Calendar", "Planner", "Organizer", "Folder", "File", "Envelope", "Stamp",
            "Courier", "Post", "Shipping", "Delivery", "Transport", "Logistics",
            "Warehouse", "Storage", "Moving", "Packing", "Unpacking", "Plumbing",
            "Carpentry", "Electrical", "Welding", "Mechanic", "Technician", "Contractor",
            "Labor", "Wages", "Salary", "Bonus", "Incentive", "Commission", "Tip",
            "Gratuity", "Donation", "Charity", "Fundraising", "Sponsorship", "Grant",
            "Scholarship", "Fellowship", "Award", "Prize", "Reward", "Refund", "Rebate",
            "Discount", "Coupon", "Voucher", "Giftcard", "Loyalty", "Points", "Miles",
            "Cashback", "Interest", "Dividend", "Rental", "Lease", "Tenant", "Landlord",
            "Agent", "Broker", "Advisor", "Consultant", "Lawyer", "Notary", "Auditor",
            "Accountant", "Tax", "Duty", "Customs", "Excise", "VAT", "GST", "Fee",
            "Charge", "Fine", "Penalty", "Late", "Overdue", "Default", "Bankruptcy",
            "Insolvency", "Liquidation", "Auction", "Foreclosure", "Repossession",
            "Eviction", "Deportation", "Visa", "Passport", "Immigration", "Citizenship",
            "Residency", "Permit", "License", "Registration", "Certification",
            "Accreditation", "Inspection", "Audit", "Compliance", "Regulation",
            "Standard", "Quality", "Safety", "Security", "Privacy", "Encryption",
            "Firewall", "Antivirus", "Backup", "Recovery", "Update", "Upgrade",
            "Maintenance", "Support", "Helpdesk", "Service", "Warranty", "Guarantee",
            "Insurance", "Assurance", "Protection", "Coverage", "Claim", "Settlement",
            "Compensation", "Damages", "Loss", "Theft", "Burglary", "Robbery", "Fraud",
            "Scam", "Cybercrime", "Hacking", "Phishing", "Malware", "Ransomware",
            "Virus", "Bug", "Error", "Crash", "Downtime", "Outage", "Blackout",
            "Brownout", "Surge", "Spike", "Fluctuation", "Voltage", "Current", "Power",
            "Energy", "Gas", "Oil", "Coal", "Nuclear", "Solar", "Wind", "Hydro",
            "Geothermal", "Biomass", "Biofuel", "Ethanol", "Biodiesel", "Hydrogen",
            "Electric", "Hybrid", "CNG", "LPG", "Propane", "Butane", "Kerosene",
            "Petrol", "Gasoline", "Octane", "Additive", "Lubricant", "Grease", "Filter",
            "Spark", "Plug", "Battery", "Alternator", "Starter", "Generator", "Inverter",
            "Converter", "Transformer", "Rectifier", "Stabilizer", "Regulator",
            "Controller", "Sensor", "Actuator", "Motor", "Engine", "Transmission",
            "Gearbox", "Clutch", "Brake", "Suspension", "Steering", "Wheel", "Tire",
            "Tube", "Rim", "Hubcap", "Cover", "Guard", "Bumper", "Fender", "Hood",
            "Trunk", "Door", "Window", "Windshield", "Wiper", "Washer", "Defogger",
            "Heater", "Cooler", "AC", "Vent", "Fan", "Blower", "Compressor",
            "Condenser", "Evaporator", "Radiator", "Thermostat", "Gauge", "Meter",
            "Display", "Screen", "Monitor", "Projector", "Speaker", "Microphone",
            "Headset", "Earphone", "Headphone", "Earbud", "Bluetooth", "WiFi",
            "Ethernet", "Fiber", "Coaxial", "Twisted", "Pair", "Satellite", "Dish",
            "Antenna", "Tower", "Base", "Station", "Router", "Switch", "Hub", "Bridge",
            "Gateway", "Modem", "Adapter", "Splitter", "Combiner", "Amplifier",
            "Attenuator", "Equalizer", "Mixer", "Synthesizer", "Sampler", "Sequencer",
            "Drum", "Machine", "Keyboard", "Piano", "Guitar", "Violin", "Cello",
            "Flute", "Saxophone", "Trumpet", "Trombone", "Drums", "Percussion",
            "Harmonica", "Accordion", "Banjo", "Mandolin", "Ukulele", "Harpsichord",
            "Organ", "Harmonium", "Tabla", "Sitar", "Veena", "Sarangi", "Santoor",
            "Shehnai", "Nadaswaram", "Mridangam", "Ghatam", "Kanjira", "Morsing",
            "Thavil", "Dholak", "Dhol", "Damaru", "Kartal", "Manjira", "Cymbals",
            "Bells", "Gong", "Chimes", "Xylophone", "Marimba", "Vibraphone",
            "Glockenspiel", "Celesta", "Theremin", "Ondes", "Martenot", "Melodica",
            "Kalimba", "Handpan", "Hang", "Steelpan", "Udu", "Pot", "Cajon", "Box",
            "Djembe", "Bongo", "Conga", "Timbale", "Bata", "Dundun", "Sabar", "Talking",
            "Frame", "Bodhran", "Tambourine", "Triangle", "Castanets", "Maracas",
            "Guiro", "Claves", "Woodblock", "Temple", "Block", "Cowbell", "Agogo",
            "Bell", "Whistle", "Siren", "Horn", "Megaphone", "Bullhorn", "Stand",
            "Case", "Strap", "Mount", "Bracket", "Clamp", "Clip", "Pin", "Hook",
            "Loop", "Ring", "Chain", "Cable", "Wire", "Cord", "String", "Rope",
            "Thread", "Yarn", "Fiber", "Filament", "Strand", "Twine", "Ribbon", "Lace",
            "Adhesive", "Epoxy", "Resin", "Cement", "Putty", "Caulk", "Sealant",
            "Filler", "Spackle", "Plaster", "Mortar", "Concrete", "Brick", "Block",
            "Tile", "Stone", "Marble", "Granite", "Slate", "Sandstone", "Limestone",
            "Travertine", "Onyx", "Quartz", "Crystal", "Gem", "Diamond", "Ruby",
            "Sapphire", "Emerald", "Topaz", "Opal", "Amethyst", "Citrine", "Peridot",
            "Garnet", "Turquoise", "Lapis", "Jade", "Pearl", "Coral", "Amber", "Ivory",
            "Bone", "Horn", "Antler", "Shell", "Feather", "Fur", "Leather", "Suede",
            "Velvet", "Satin", "Silk", "Linen", "Cotton", "Wool", "Polyester", "Nylon",
            "Rayon", "Acrylic", "Spandex", "Denim", "Canvas", "Tweed", "Twill",
            "Corduroy", "Flannel", "Fleece", "Terry", "Velour", "Chiffon", "Georgette",
            "Crepe", "Organza", "Taffeta", "Brocade", "Damask", "Jacquard", "Mesh",
            "Net", "Voile", "Batiste", "Muslin", "Calico", "Gingham", "Paisley",
            "Plaid", "Striped", "Dotted", "Floral", "Abstract", "Geometric", "Animal",
            "Print", "Camouflage", "Tie-dye", "Batik", "Embroidery", "Applique",
            "Beadwork", "Sequins", "Rhinestones", "Studs", "Spikes", "Rivets",
            "Buttons", "Zippers", "Snaps", "Hooks", "Eyes", "Buckles", "Clasps",
            "Toggles", "Fasteners", "Closures", "Openings", "Necklines", "Collars",
            "Lapels", "Cuffs", "Hemlines", "Seams", "Darts", "Pleats", "Tucks",
            "Gathers", "Ruffles", "Frills", "Flounces", "Trains", "Bustles",
            "Crinolines", "Hoop", "Petticoat", "Corset", "Girdle", "Bra", "Panties",
            "Boxers", "Briefs", "Thong", "Bikini", "Swimsuit", "Trunks", "Board",
            "Shorts", "Wetsuit", "Rash", "Guard", "Goggles", "Cap", "Fins", "Snorkel",
            "Mask", "Regulator", "Tank", "Buoyancy", "Compensator", "Weight", "Dive",
            "Computer", "Depth", "Compass", "Knife", "Light", "Camera", "Housing",
            "Strobe", "Video", "Lens", "Filter", "Tripod", "Monopod", "Selfie", "Stick",
            "Gimbal", "Stabilizer", "Drone", "Quadcopter", "Hexacopter", "Octocopter",
            "Helicopter", "Airplane", "Glider", "Balloon", "Blimp", "Zeppelin",
            "Rocket", "Missile", "Spacecraft", "Shuttle", "Probe", "Rover", "Lander",
            "Orbiter", "Flyby", "Gravity", "Assist", "Slingshot", "Trajectory",
            "Orbit", "Altitude", "Velocity", "Acceleration", "Deceleration", "Braking",
            "Thrust", "Lift", "Drag", "Mass", "Density", "Volume", "Pressure",
            "Temperature", "Humidity", "Moisture", "Dew", "Point", "Frost", "Ice",
            "Snow", "Sleet", "Hail", "Rain", "Drizzle", "Shower", "Storm", "Thunder",
            "Lightning", "Tornado", "Hurricane", "Cyclone", "Typhoon", "Monsoon",
            "Flood", "Drought", "Famine", "Epidemic", "Pandemic", "Plague", "Infection",
            "Disease", "Illness", "Sickness", "Ailment", "Disorder", "Syndrome",
            "Condition", "Symptom", "Sign", "Indicator", "Marker", "Signal", "Alert",
            "Alarm", "Warning", "Caution", "Danger", "Hazard", "Risk", "Threat",
            "Peril", "Jeopardy", "Crisis", "Emergency", "Disaster", "Catastrophe",
            "Calamity", "Tragedy", "Mishap", "Accident", "Incident", "Event",
            "Occurrence", "Happening", "Situation", "Circumstance", "Context",
            "Environment", "Setting", "Background", "Foreground", "Middleground",
            "Perspective", "Viewpoint", "Standpoint", "Position", "Location", "Place",
            "Site", "Spot", "Area", "Region", "Zone", "District", "Sector", "Quarter",
            "Precinct", "Ward", "Division", "Section", "Segment", "Part", "Portion",
            "Piece", "Bit", "Fragment", "Shard", "Splinter", "Sliver", "Chip", "Flake",
            "Grain", "Speck", "Dot", "Stain", "Mark", "Blemish", "Flaw", "Defect",
            "Fault", "Mistake", "Blunder", "Oversight", "Omission", "Neglect",
            "Carelessness", "Inattention", "Distraction", "Interruption", "Disruption",
            "Disturbance", "Interference", "Obstruction", "Blockage", "Clog", "Jam",
            "Stuck", "Wedged", "Lodged", "Embedded", "Implanted", "Inserted", "Injected",
            "Infused", "Instilled", "Imbued", "Suffused", "Permeated", "Saturated",
            "Soaked", "Drenched", "Drowned", "Submerged", "Immersed", "Dip", "Dunk",
            "Plunge", "Jump", "Leap", "Bound", "Spring", "Vault", "Hurdle", "Clear",
            "Cross", "Traverse", "Navigate", "Pilot", "Steer", "Guide", "Direct",
            "Lead", "Follow", "Chase", "Pursue", "Track", "Trace", "Trail", "Shadow",
            "Stalk", "Hunt", "Prey", "Predator", "Hunter", "Gatherer", "Forager",
            "Scavenger", "Carrion", "Scrap", "Leftover", "Remnant", "Residue",
            "Sediment", "Deposit", "Accumulation", "Aggregation", "Collection",
            "Assemblage", "Cluster", "Group", "Bunch", "Batch", "Lot", "Set", "Kit",
            "Pack", "Stack", "Pile", "Heap", "Mound", "Mountain", "Hill", "Knoll",
            "Ridge", "Peak", "Summit", "Crest", "Top", "Apex", "Vertex", "Zenith",
            "Pinnacle", "Acme", "Climax", "Culmination", "Finale", "End", "Finish",
            "Conclusion", "Completion", "Termination", "Cessation", "Stoppage", "Halt",
            "Pause", "Break", "Intermission", "Interval", "Interlude", "Respite",
            "Rest", "Relaxation", "Leisure", "Recreation", "Entertainment", "Amusement",
            "Diversion", "Pastime", "Hobby", "Avocation", "Pursuit", "Enterprise",
            "Venture", "Project", "Scheme", "Plan", "Plot", "Conspiracy", "Intrigue",
            "Machination", "Maneuver", "Tactic", "Strategy", "Approach", "Method",
            "Technique", "Procedure", "Process", "System", "Regimen", "Routine",
            "Habit", "Custom", "Tradition", "Convention", "Norm", "Criterion",
            "Benchmark", "Metric", "Measure", "Gauge", "Scale", "Range", "Scope",
            "Extent", "Degree", "Level", "Tier", "Rank", "Grade", "Category", "Kind",
            "Sort", "Variety", "Species", "Genus", "Family", "Order", "Phylum",
            "Kingdom", "Domain", "Realm", "Sphere", "Circle", "Round", "Coil", "Spiral",
            "Helix", "Corkscrew", "Spring", "Link", "Connector", "Joint", "Coupling",
            "Union", "Fitting", "Fixture", "Support", "Brace", "Strut", "Beam",
            "Girder", "Truss", "Framework", "Skeleton", "Casing", "Enclosure", "Vessel",
            "Receptacle", "Repository", "Depository", "Silo", "Tank", "Vat", "Barrel",
            "Keg", "Cask", "Firkin", "Hogshead", "Butt", "Tun", "Prism", "Cube",
            "Crate", "Coffer", "Strongbox", "Safe", "Locker", "Cabinet", "Cupboard",
            "Wardrobe", "Armoire", "Dresser", "Bureau", "Commode", "Chiffonier",
            "Highboy", "Lowboy", "Tallboy", "Secretary", "Escritoire", "Desk", "Table",
            "Pedestal", "Foundation", "Footing", "Plinth", "Socle", "Dado", "Wainscot",
            "Paneling", "Cladding", "Siding", "Facade", "Front", "Face", "Surface",
            "Exterior", "Interior", "Inside", "Outside", "Topside", "Underside",
            "Bottom", "Bedrock", "Substrate", "Matrix", "Medium", "Milieu", "Ambience",
            "Atmosphere", "Aura", "Vibe", "Mood", "Tone", "Tenor", "Spirit", "Essence",
            "Core", "Heart", "Soul", "Center", "Middle", "Midpoint", "Median",
            "Average", "Mean", "Mode", "Paradigm", "Model", "Pattern", "Template",
            "Prototype", "Archetype", "Ideal", "Perfect", "Flawless", "Impeccable",
            "Pristine", "Immaculate", "Spotless", "Clean", "Pure", "Clear",
            "Transparent", "Translucent", "Opaque", "Cloudy", "Hazy", "Foggy", "Misty",
            "Murky", "Turbid", "Muddy", "Silty", "Sandy", "Gravelly", "Rocky", "Stony",
            "Pebbly", "Shingly", "Bouldery", "Mountainous", "Hilly", "Rolling",
            "Undulating", "Wavy", "Curvy", "Bendy", "Twisty", "Winding", "Meandering",
            "Serpentine", "Sinuous", "Curvilinear", "Rectilinear", "Linear", "Straight",
            "Direct", "Angle", "Obtuse", "Acute", "Degree", "Radian", "Gradient",
            "Slope", "Incline", "Decline", "Ascent", "Descent", "Climb", "Drop",
            "Fall", "Descend", "Ascend", "Rise", "Lift", "Elevate", "Raise", "Lower",
            "Reduce", "Decrease", "Increase", "Augment", "Expand", "Extend", "Lengthen",
            "Shorten", "Shrink", "Contract", "Compress", "Compact", "Dense", "Solid",
            "Firm", "Hard", "Soft", "Gentle", "Mild", "Moderate", "Temperate",
            "Balanced", "Equilibrium", "Stability", "Steadiness", "Constancy",
            "Consistency", "Uniformity", "Regularity", "Predictability", "Reliability",
            "Dependability", "Trustworthiness", "Credibility", "Believability",
            "Plausibility", "Probability", "Possibility", "Potential", "Capability",
            "Capacity", "Ability", "Competence", "Proficiency", "Expertise", "Mastery",
            "Skill", "Talent", "Gift", "Aptitude", "Flair", "Knack", "Bent", "Leaning",
            "Inclination", "Tendency", "Trend", "Direction", "Course", "Path", "Route",
            "Way", "Road", "Street", "Avenue", "Boulevard", "Highway", "Freeway",
            "Expressway", "Turnpike", "Parkway", "Drive", "Lane", "Alley", "Byway",
            "Pathway", "Walkway", "Sidewalk", "Pavement", "Footpath", "Bearing",
            "Heading", "Orientation", "Alignment", "Arrangement", "Order", "Sequence",
            "Series", "Succession", "Progression", "Development", "Evolution", "Growth",
            "Expansion", "Extension", "Proliferation", "Multiplication", "Reproduction",
            "Propagation", "Dissemination", "Distribution", "Dispersion", "Scattering",
            "Spreading", "Diffusion", "Osmosis", "Dialysis", "Filtration", "Separation",
            "Division", "Partition", "Segmentation", "Compartmentalization",
            "Categorization", "Classification", "Taxonomy", "Nomenclature",
            "Terminology", "Vocabulary", "Lexicon", "Glossary", "Dictionary",
            "Thesaurus", "Encyclopedia", "Compendium", "Anthology", "Compilation",
            "Aggregate", "Totality", "Whole", "Entirety", "Full", "Total", "Absolute",
            "Utter", "Thorough", "Comprehensive", "Exhaustive", "Inclusive", "Omnibus",
            "Catch", "All", "Umbrella", "Blanket", "Generic", "General", "Specific",
            "Particular", "Individual", "Personal", "Private", "Confidential", "Secret",
            "Classified", "Restricted", "Limited", "Bound", "Confined", "Contained",
            "Encapsulated", "Wrapped", "Covered", "Shrouded", "Veiled", "Masked",
            "Disguised", "Camouflaged", "Hidden", "Concealed", "Obscured", "Blocked",
            "Barred", "Barricaded", "Fortified", "Strengthened", "Reinforced",
            "Buttressed", "Supported", "Propped", "Shored", "Braced", "Stayed",
            "Guyed", "Anchored", "Moor", "Groceries", "Vegetables", "Fruits", "Milk",
            "Bread", "Eggs", "Snacks", "Beverages", "Packaged", "Toiletries",
            "Electricity", "Water", "Cylinder", "House", "Charges", "Laundry", "Home",
            "Appliances", "Public", "Cab", "Fare", "Car", "Parking", "Fees", "Vehicle",
            "Loan", "Toll", "Metro", "Recharge", "Uber", "School", "Tuition", "Toys",
            "Baby", "Care", "Pocket", "Money", "Daycare", "Family", "Outing", "Kids",
            "Gifts", "Hobby", "Classes", "Restaurant", "Street", "Cafe", "Online",
            "Fast", "Buffet", "Party", "Dinner", "Ice", "Cream", "Takeaway",
            "Clothing", "Footwear", "Haircut", "Salon", "Cosmetics", "Makeup", "Spa",
            "Tailoring", "Accessories", "Skin", "Medicines", "Doctor", "Visit",
            "Health", "Lab", "Tests", "Dental", "First", "Aid", "Supplements",
            "Therapy", "Eye", "Checkup", "Gym", "Office", "Supplies", "Business",
            "Travel", "Client", "Freelance", "Services", "Software", "Subscriptions",
            "Web", "Hosting", "Coworking", "Laptop", "Marketing", "Printing", "Mobile",
            "New", "Phone", "Headphones", "Chargers", "Streaming", "Course", "E-books",
            "Cloud", "Storage", "Pet", "Grooming", "Donations", "Birthday",
            "Anniversary", "Gift", "Vacation", "Booking", "Event", "Tickets",
            "Repayment", "Credit", "Card"
    ));

}
